version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/insurancepolicydatabase
      SPRING_DATASOURCE_USERNAME: policyusername
      SPRING_DATASOURCE_PASSWORD: 987654321
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: insurancepolicydatabase
      POSTGRES_USER: policyusername
      POSTGRES_PASSWORD: 987654321
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: